---
- name: Gather information about template droplet
  community.digitalocean.digital_ocean_droplet_info:
    name: "{{ template_dp_name }}"
  register: templatedp

- name: Snapshot a Droplet
  community.digitalocean.digital_ocean_snapshot:
    state: present
    snapshot_type: droplet
    droplet_id: "{{ item.id }}"
    snapshot_name: "{{ snapshot_name }}"
    wait_timeout: 300
  with_items: "{{ templatedp.data }}"
  register: snapshotcreated
  when: create_snapshot == true

- name: Gather droplet's snapshot list
  community.digitalocean.digital_ocean_droplet_info:
    name: "{{ template_dp_name }}"
  register: snapshotlist

- set_fact:
    snapshotidfromdroplet: "{{ item.snapshot_ids[-1] }}"
  with_items: "{{ snapshotlist.data }}"

- debug: msg="{{ snapshotcreated.results[0].item.snapshot_ids[-1]  }}"
  when: create_snapshot == true

- debug: msg="{{ item.snapshot_ids[-1] }}"
  with_items: "{{ snapshotlist.data }}"

- name: create droplet using image
  include_role:
    name: droplet_creation
  vars:
    image: "{{ snapshotidfromdroplet if snapshot_id ==0 else snapshot_id}}"
    droplets_count: "{{ droplets_count }}"
    droplet_name: "{{ droplet_prefix }}"
  when: create_snapshot != true