---
- name: Gather information about template droplet
  community.digitalocean.digital_ocean_droplet_info:
    name: "{{ template_dp_name }}"
  register: templatedp
  when: create_snapshot

- name: stop service
  systemd:
    name: '{{ litecoin__service }}'
    enabled: false
    state: stopped
  when: ready_template_node

- name: Remove Data directory
  become: true
  file:
    state: absent
    path: '{{ litecoin__data_dir }}'
  when: ready_template_node

- name: Snapshot a Droplet
  community.digitalocean.digital_ocean_snapshot:
    state: present
    snapshot_type: droplet
    droplet_id: "{{ item.id }}"
    snapshot_name: "{{ snapshot_name }}"
    wait_timeout: 300
  with_items: "{{ templatedp.data }}"
  register: snapshotcreated
  when: create_snapshot

- name: Gather droplet's snapshot list
  community.digitalocean.digital_ocean_droplet_info:
    name: "{{ template_dp_name }}"
  register: snapshotlist
  when: create_nodes_from_snapshot

- set_fact:
    snapshotidfromdroplet: "{{ item.snapshot_ids[-1] }}"
  with_items: "{{ snapshotlist.data }}"
  when: create_nodes_from_snapshot

- debug: msg="{{ item.snapshot_ids[-1] }}"
  with_items: "{{ snapshotlist.data }}"
  when: create_nodes_from_snapshot

- name: create droplet using image
  include_role:
    name: droplet_creation
  vars:
    image: "{{ snapshotidfromdroplet if snapshot_id ==0 else snapshot_id}}"
    droplets_count: "{{ droplets_count }}"
    droplet_name: "{{ droplet_prefix }}"
  when: create_nodes_from_snapshot

- name: restore data dir from backup
  include_role:
    name: backup
  vars:
    restore: true
  when: restore_data