---
- hosts: localhost
  connection: local
  gather_facts: false

  roles:
  - droplet_creation

- hosts: ltc_nodes
  gather_facts: false
  remote_user: root

  roles:
    - { role: snapshot, ready_template_node: true}